/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "teste_downto.v:25" *)
module teste_downto(input_bus, output_bus);
  (* src = "teste_downto.v:26" *)
  input [7:0] input_bus;
  (* src = "teste_downto.v:27" *)
  output [0:7] output_bus;
  assign output_bus = input_bus;
endmodule
