/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module array_example(addr, dout);
  input [1:0] addr;
  wire [1:0] addr;
  output [7:0] dout;
  wire [7:0] dout;
  wire [31:0] mem;
  wire [1:0] n3_o;
  wire [7:0] n7_data;
  reg [7:0] n6 [3:0];
  initial begin
    n6[3] = 8'h01;
    n6[2] = 8'h02;
    n6[1] = 8'h04;
    n6[0] = 8'h08;
  end
  assign dout = n6[n3_o];
  assign n3_o = 2'h3 - addr;
  assign mem = 32'd16909320;
  assign n7_data = dout;
endmodule
