/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module clocked_example(clk, d, q);
  input clk;
  wire clk;
  input d;
  wire d;
  reg n6_q;
  output q;
  wire q;
  always @(posedge clk)
    n6_q <= d;
  assign q = n6_q;
endmodule
