/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module clocked_array_example(clk, addr, q);
  wire [3:0] _0_;
  input addr;
  wire addr;
  input clk;
  wire clk;
  reg [3:0] n14_data;
  wire n6_o;
  output [3:0] q;
  wire [3:0] q;
  wire [7:0] r;
  reg [3:0] n12 [1:0];
  initial begin
    n12[1] = 4'h1;
    n12[0] = 4'h2;
  end
  assign _0_ = n12[n6_o];
  always @(posedge clk)
    n14_data <= _0_;
  assign n6_o = 1'h1 - addr;
  assign q = n14_data;
  assign r = 8'h12;
endmodule
