/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module downto_example(a, y);
  input [7:0] a;
  wire [7:0] a;
  wire n1_o;
  output y;
  wire y;
  assign n1_o = a[7];
  assign y = a[7];
endmodule
