/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module integer_example(clk, rst, counter);
  wire _0_;
  wire [1:0] c;
  input clk;
  wire clk;
  output [1:0] counter;
  wire [1:0] counter;
  wire [31:0] n10_o;
  wire [1:0] n11_o;
  reg [1:0] n18_q = 2'h0;
  wire [31:0] n5_o;
  wire n7_o;
  wire [31:0] n8_o;
  input rst;
  wire rst;
  assign n10_o = { 30'h00000000, n18_q } + 32'd1;
  always @(posedge clk)
    if (_0_) n18_q <= 2'h0;
    else n18_q <= n10_o[1:0];
  assign _0_ = | { n7_o, rst };
  assign n7_o = n18_q == 2'h3;
  assign c = n18_q;
  assign counter = n18_q;
  assign n11_o = n10_o[1:0];
  assign n5_o = { 30'h00000000, n18_q };
  assign n8_o = { 30'h00000000, n18_q };
endmodule
